//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex05.Connect4UI.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ex05.Connect4UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }

            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button {
            get {
                object obj = ResourceManager.GetObject("Button", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonDown {
            get {
                object obj = ResourceManager.GetObject("ButtonDown", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonHover {
            get {
                object obj = ResourceManager.GetObject("ButtonHover", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChipHighlight {
            get {
                object obj = ResourceManager.GetObject("ChipHighlight", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChipRed {
            get {
                object obj = ResourceManager.GetObject("ChipRed", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChipYellow {
            get {
                object obj = ResourceManager.GetObject("ChipYellow", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reload {
            get {
                object obj = ResourceManager.GetObject("Reload", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another round?.
        /// </summary>
        internal static string TextAnotherRound {
            get {
                return ResourceManager.GetString("TextAnotherRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        internal static string TextBack {
            get {
                return ResourceManager.GetString("TextBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Boomer View.
        /// </summary>
        internal static string TextBackToBoomer {
            get {
                return ResourceManager.GetString("TextBackToBoomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boomer Error.
        /// </summary>
        internal static string TextBoomerError {
            get {
                return ResourceManager.GetString("TextBoomerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string TextCancel {
            get {
                return ResourceManager.GetString("TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring game....
        /// </summary>
        internal static string TextConfiguring {
            get {
                return ResourceManager.GetString("TextConfiguring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Four.
        /// </summary>
        internal static string TextConnectFour {
            get {
                return ResourceManager.GetString("TextConnectFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Four (Boomer View).
        /// </summary>
        internal static string TextConnectFourBoomer {
            get {
                return ResourceManager.GetString("TextConnectFourBoomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a draw!.
        /// </summary>
        internal static string TextDraw {
            get {
                return ResourceManager.GetString("TextDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TextExit {
            get {
                return ResourceManager.GetString("TextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string TextExitConfirmation {
            get {
                return ResourceManager.GetString("TextExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string TextGame {
            get {
                return ResourceManager.GetString("TextGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string TextGameOver {
            get {
                return ResourceManager.GetString("TextGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to serious view.
        /// </summary>
        internal static string TextGoToSeriousView {
            get {
                return ResourceManager.GetString("TextGoToSeriousView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string TextHelp {
            get {
                return ResourceManager.GetString("TextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string TextHome {
            get {
                return ResourceManager.GetString("TextHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Player.
        /// </summary>
        internal static string TextMultiPlayer {
            get {
                return ResourceManager.GetString("TextMultiPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is mandatory.
        /// </summary>
        internal static string TextNameIsMandatory {
            get {
                return ResourceManager.GetString("TextNameIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to redo.
        /// </summary>
        internal static string TextNothingToRedo {
            get {
                return ResourceManager.GetString("TextNothingToRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to undo.
        /// </summary>
        internal static string TextNothingToUndo {
            get {
                return ResourceManager.GetString("TextNothingToUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is {0}&apos;s turn.
        /// </summary>
        internal static string TextNotYourTurn {
            get {
                return ResourceManager.GetString("TextNotYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TextOk {
            get {
                return ResourceManager.GetString("TextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        internal static string TextPc {
            get {
                return ResourceManager.GetString("TextPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string TextPlayerScore {
            get {
                return ResourceManager.GetString("TextPlayerScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s turn.
        /// </summary>
        internal static string TextPlayerTurn {
            get {
                return ResourceManager.GetString("TextPlayerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string TextReady {
            get {
                return ResourceManager.GetString("TextReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string TextRedo {
            get {
                return ResourceManager.GetString("TextRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string TextRestart {
            get {
                return ResourceManager.GetString("TextRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string TextStart {
            get {
                return ResourceManager.GetString("TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string TextUndo {
            get {
                return ResourceManager.GetString("TextUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating settings....
        /// </summary>
        internal static string TextValidatingSettings {
            get {
                return ResourceManager.GetString("TextValidatingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} won!.
        /// </summary>
        internal static string TextWin {
            get {
                return ResourceManager.GetString("TextWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Title {
            get {
                object obj = ResourceManager.GetObject("Title", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
